plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - "vendor/**/*"
    - "coverage/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

RSpec/ExampleLength:
  Max: 12

RSpec/MultipleExpectations:
  Max: 5

