# frozen_string_literal: true

require 'date'
require 'fileutils'
require 'json'
require 'pathname'
require 'time'

module PolishOpenSourceRank
  def self.root
    Pathname(__dir__).parent
  end
end

require_relative 'polish_open_source_rank/configuration'
require_relative 'polish_open_source_rank/domain/location_catalog'
require_relative 'polish_open_source_rank/domain/location_classifier'
require_relative 'polish_open_source_rank/application/month_period'
require_relative 'polish_open_source_rank/application/source_not_found'
require_relative 'polish_open_source_rank/application/discord_invite_join'
require_relative 'polish_open_source_rank/application/discord_invite_use_detector'
require_relative 'polish_open_source_rank/application/monthly_snapshot_job'
require_relative 'polish_open_source_rank/infrastructure/github/client'
require_relative 'polish_open_source_rank/infrastructure/github/gateway'
require_relative 'polish_open_source_rank/infrastructure/gitlab/client'
require_relative 'polish_open_source_rank/infrastructure/gitlab/gateway'
require_relative 'polish_open_source_rank/infrastructure/codeberg/client'
require_relative 'polish_open_source_rank/infrastructure/codeberg/gateway'
require_relative 'polish_open_source_rank/infrastructure/platform_schema_migration'
require_relative 'polish_open_source_rank/infrastructure/sqlite_run_lifecycle'
require_relative 'polish_open_source_rank/infrastructure/sqlite_job_progress'
require_relative 'polish_open_source_rank/infrastructure/ranking_pruner'
require_relative 'polish_open_source_rank/infrastructure/sqlite_schema'
require_relative 'polish_open_source_rank/infrastructure/sqlite_store'
require_relative 'polish_open_source_rank/infrastructure/discord_invite_bot'
require_relative 'polish_open_source_rank/infrastructure/monthly_snapshot_composition'
require_relative 'polish_open_source_rank/application/monthly_snapshot_command'
require_relative 'polish_open_source_rank/web/auth/discord_gateway'
require_relative 'polish_open_source_rank/web/auth/discord_oauth_client'
require_relative 'polish_open_source_rank/web/auth/discord_role_map'
require_relative 'polish_open_source_rank/web/auth/github_oauth_client'
